name: "Test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["20.18.1", "20.18.2", 22, 23]
    steps:
      - uses: actions/checkout@v4
      - name: "Install Node ${{ matrix.node }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: "Install Deps"
        run: npm install
      - name: "Test"
        run: npx vitest
